// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXe7LEQUZx7IlC6SQfqEa_VeOpjl6HpdM',
    appId: '1:656204592092:web:3c13803876dd499c811519',
    messagingSenderId: '656204592092',
    projectId: 'argraduateapp',
    authDomain: 'argraduateapp.firebaseapp.com',
    storageBucket: 'argraduateapp.appspot.com',
    measurementId: 'G-Z0V7XS0RTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy6Vlo7tLehFOS1m2fqclh6-v_KDjo5WA',
    appId: '1:656204592092:android:66061cdbbf44c7b2811519',
    messagingSenderId: '656204592092',
    projectId: 'argraduateapp',
    storageBucket: 'argraduateapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbGgQ19g1Ey3v8N1n7Tl2bKVwqse7SXak',
    appId: '1:656204592092:ios:dc3ae52fe497df11811519',
    messagingSenderId: '656204592092',
    projectId: 'argraduateapp',
    storageBucket: 'argraduateapp.appspot.com',
    iosBundleId: 'com.example.flutterArApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbGgQ19g1Ey3v8N1n7Tl2bKVwqse7SXak',
    appId: '1:656204592092:ios:dc3ae52fe497df11811519',
    messagingSenderId: '656204592092',
    projectId: 'argraduateapp',
    storageBucket: 'argraduateapp.appspot.com',
    iosBundleId: 'com.example.flutterArApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXe7LEQUZx7IlC6SQfqEa_VeOpjl6HpdM',
    appId: '1:656204592092:web:8da74dc87d227d7c811519',
    messagingSenderId: '656204592092',
    projectId: 'argraduateapp',
    authDomain: 'argraduateapp.firebaseapp.com',
    storageBucket: 'argraduateapp.appspot.com',
    measurementId: 'G-TX484TRZB2',
  );
}
